# Generated by Django 3.1.2 on 2020-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='isdone',
        ),
    ]
