# Generated by Django 3.1.2 on 2020-10-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.BooleanField()),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.buy')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashSeller', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
